### ISSUE TITLE
Full Search Results component

### ISSUE THREAD

**Issue by iurimatias** [status-im/StatusQ#264]
note: status-desktop contains the messages portion of this component which could potentially be moved here

<img width="435" alt="Screen Shot 2021-07-15 at 1 21 40 PM" src="https://user-images.githubusercontent.com/176720/125830521-6d686686-6c29-43bf-bba9-1e9a0fa358cf.png">

https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/💬-Chat⎜Desktop?node-id=6042%3A1

**Comment by saledjenic** [comment]
@simonricoo please see point 2 in my comment [here](https://github.com/status-im/StatusQ/pull/301#issuecomment-894073522) since user should be able to select either "Anywhere" or whole chat/community section or any chat from the chat section or any channel from community section, as a location where to search in, I am not sure if selection whole chat/community section is intuitive enough cause they are menu, what do you think?

_This is just a proposal, have splitted menus_:

In: &nbsp; Anywhere &#5121;

In: &nbsp; Chat &#5121; &nbsp;&nbsp; Select Chat &#5121; &nbsp;&nbsp; X

In: &nbsp; Chat &#5121; &nbsp;&nbsp; vitalik.eth &#5121; &nbsp;&nbsp; X

In: &nbsp; CryptoKitties &#5121; &nbsp;&nbsp; Select Channel &#5121; &nbsp;&nbsp; X

In: &nbsp; CryptoKitties &#5121; &nbsp;&nbsp; #general &#5121; &nbsp;&nbsp; X
