### ISSUE TITLE
Need play/pause button for voice messages

### ISSUE THREAD

**Issue by pinebit** [status-im/StatusQ#310]
https://www.figma.com/file/MtAO3a7HnEH5xjCDVNilS7/%F0%9F%8E%A8-Design-System-%E2%8E%9C-Desktop?node-id=1906%3A29712

1. There are no icons in assets that represent *filled* play and pause actions.
2. The standard palette for StatusFlatRoundButton does not meet the design. Maybe we should introduce a new palette config?

**Comment by PascalPrecht** [comment]
Sorry @pinebit for the late reply. Seeing this just now...

Re: 1: no problem will add those.
Re: 2: Can elaborate by what you mean by that? There are two variations of the flat round button which are both implemented as per design system. Maybe you're referring to a different component?

**Comment by PascalPrecht** [comment]
I see! Yes, those are different variations or even specific to just audio messages.

**Comment by pinebit** [comment]
My intention was to use StatusQ components when building a new UI. Is that correct? Of course I could have built yet-another-button, but I want to avoid code duplication.

**Comment by PascalPrecht** [comment]
You can try using `StatusRoundFlatButton` in either Primary or Secondary type (need to check which one is closer) and then you can try adjusting it to your needs by overriding properties. Otherwise it'd be a new component.

Ideally however, these audio message components are provided by StatusQ then you don't have to worry about that. But I understand you wanna move quickly on your end.

I'd propose you try you luck with the flat round button from StatusQ and build whatever you need and later we move that thing you've built to StatusQ (and fine-tune/adjust it if needed)

**Comment by pinebit** [comment]
I am afraid I won't be able to just tune StatusRoundFlatButton, because for example
```
    QtObject {
        id: backgroundSettings
```
is internal id and I don't have access to it.

> need to check which one is closer
Yes, this is what I did already in my work.

Let's have the new icons for now (filled play/pause).
Then we will wait for recording UI provided by Simon, then I will create/add new components to StatusQ.
