### ISSUE TITLE
password component

### ISSUE THREAD

**Issue by iurimatias** [status-im/StatusQ#529]
figma: https://www.figma.com/file/IPpvkpDWabBKJTeo6bFop0/Kuba%E2%8E%9CDesktop?node-id=1965%3A218456

![Screen Shot 2022-01-12 at 4 19 51 PM](https://user-images.githubusercontent.com/176720/149223153-1132b6c6-833f-4490-8625-dd6043a85a62.png)

![Screen Shot 2022-01-12 at 4 20 02 PM](https://user-images.githubusercontent.com/176720/149223174-6596595e-ef72-4bc1-837f-e84058dbfc07.png)

**Comment by 0x-r4bbit** [comment]
I guess this can be closed since this is essentially status-im/status-desktop#7574, or a variation of that.

For the person implementing this: `StatusInput` already supports rendering a component on the left hand side inside the input. So all we really have to do is make `echoMode` possible.

This can be closed as duplicate.
